language: python
python:
  - "2.7"
before_install:
  sudo apt-get install -y python-setuptools libxml2 libxslt1-dev python-dev
install: "pip install tinycss requests grequests"
script:  python test/tests_unittest.py
